import type { CivicCase } from "./types.ts";

export const caseBank: readonly CivicCase[] = [
  {
    id: "fictional-safety-sign-bill-reconsideration",
    kind: "bill",
    title: "가상 안전 표지 지원 법률안",
    shortTitle: "법률안 재의",
    description:
      "어린이용 빛반사 안전 표지를 돕는 가상 법률안이 여러 국가기관을 차례로 거쳐요.",
    learningFocus: "재의 요구는 법률안을 없애는 일이 아니라 국회에 다시 살펴 달라고 돌려보내는 절차예요.",
    initialStateId: "draft-prepared",
    institutions: ["executive", "national-assembly"],
    legalSourceIds: ["constitution-40", "constitution-52-53"],
    states: [
      { id: "draft-prepared", title: "정부가 법률안을 준비했어요", documentType: "법률안 초안", actor: "정부", effect: "아직 법률의 효력이 없어요.", nextNeed: "국회에 제출해야 해요.", answerPosition: 0 },
      { id: "submitted-to-assembly", title: "법률안이 국회에 제출됐어요", documentType: "제출된 법률안", actor: "정부 → 국회", effect: "아직 법률로 확정되지 않았어요.", nextNeed: "국회의 심의·의결이 필요해요.", answerPosition: 1 },
      { id: "passed-by-assembly", title: "국회가 법률안을 의결했어요", documentType: "의결된 법률안", actor: "국회", effect: "대통령에게 이송된 상태예요.", nextNeed: "공포 또는 재의 요구 절차가 이어져요.", answerPosition: 2 },
      { id: "returned-for-reconsideration", title: "국회가 다시 살펴볼 차례예요", documentType: "재의 요구된 법률안", actor: "대통령 → 국회", effect: "법률안은 사라지지 않았고 국회로 돌아왔어요.", nextNeed: "국회가 재의 절차를 진행해요." },
      { id: "promulgated-after-repassage", title: "재의결된 법률안이 공포됐어요", documentType: "공포된 법률", actor: "국회·대통령", effect: "헌법상 절차를 거쳐 법률이 되었어요.", nextNeed: "이 사건의 법률안 절차가 끝났어요.", terminal: true },
      { id: "bill-closed-without-repassage", title: "재의결 없이 절차가 끝났어요", documentType: "종료된 법률안", actor: "국회", effect: "법률로 공포되지 않고 절차가 끝났어요.", nextNeed: "이 선택도 헌법상 가능한 종료예요.", terminal: true },
    ],
    transitions: [
      { id: "bill-submit", fromStateId: "draft-prepared", actionId: "government-submits-bill", institutionId: "executive", specificActor: "정부", actionText: "법률안을 국회에 제출해요", toStateId: "submitted-to-assembly", relationLabel: "법률안 제출", effectText: "정부가 법률안을 국회에 제출했어요.", limitText: "정부가 제출할 수 있지만 법률안을 최종 의결하지는 않아요.", legalSourceIds: ["constitution-52-53"] },
      { id: "bill-pass", fromStateId: "submitted-to-assembly", actionId: "assembly-deliberates-bill", institutionId: "national-assembly", specificActor: "국회", actionText: "법률안을 심의·의결해요", toStateId: "passed-by-assembly", relationLabel: "심의·의결", effectText: "국회가 내용을 살펴 법률안을 의결했어요.", limitText: "국회는 의결하지만 행정 사업을 직접 운영하지 않아요.", legalSourceIds: ["constitution-40", "constitution-52-53"] },
      { id: "bill-return", fromStateId: "passed-by-assembly", actionId: "president-requests-reconsideration", institutionId: "executive", specificActor: "대통령", actionText: "이유를 붙여 국회에 재의를 요구해요", toStateId: "returned-for-reconsideration", relationLabel: "재의 요구", effectText: "법률안이 국회로 돌아가 다시 심의할 수 있는 상태가 되었어요.", limitText: "대통령이 법률안을 영구히 없애는 행동은 아니에요.", legalSourceIds: ["constitution-52-53"], prediction: { question: "재의 요구를 받으면 법률안은 어떻게 될까요?", options: [{ id: "return", text: "국회로 돌아가 다시 심의할 수 있어요." }, { id: "delete", text: "대통령이 법률안을 영구 삭제해요." }], correctId: "return", explanation: "재의 요구는 이유를 붙여 국회에 다시 심의해 달라고 돌려보내는 절차예요." } },
      { id: "bill-repass", fromStateId: "returned-for-reconsideration", actionId: "assembly-repasses-bill", institutionId: "national-assembly", specificActor: "국회", actionText: "헌법상 더 엄격한 요건으로 재의결해요", toStateId: "promulgated-after-repassage", relationLabel: "재의결·공포", effectText: "사건 자료가 재의결 요건 충족을 알려 주어 법률이 공포됐어요.", limitText: "정족수 계산은 이 활동에서 평가하지 않아요.", legalSourceIds: ["constitution-52-53"], completesCase: true },
      { id: "bill-close", fromStateId: "returned-for-reconsideration", actionId: "assembly-does-not-repass", institutionId: "national-assembly", specificActor: "국회", actionText: "재의결하지 않고 절차를 마쳐요", toStateId: "bill-closed-without-repassage", relationLabel: "절차 종료", effectText: "재의결하지 않아 법률안 절차가 끝났어요.", limitText: "정책 실패 점수가 아니라 헌법상 가능한 다른 종료예요.", legalSourceIds: ["constitution-52-53"], completesCase: true },
    ],
    misconceptions: [
      { id: "court-passes-bill", stateId: "draft-prepared", institutionId: "court", specificActor: "법원", actionText: "법률안을 통과시켜요", feedback: "법원은 구체적인 다툼을 재판해요. 법률안을 살펴보고 결정하는 곳은 국회예요." },
      { id: "assembly-runs-program", stateId: "draft-prepared", institutionId: "national-assembly", specificActor: "국회", actionText: "안전 표지 사업을 바로 운영해요", feedback: "아직 법률안이 국회에 제출되지 않았어요. 먼저 정부가 법률안을 국회에 내야 해요." },
      { id: "government-finalizes-bill", stateId: "submitted-to-assembly", institutionId: "executive", specificActor: "정부", actionText: "제출한 법률안을 스스로 확정해요", feedback: "정부는 법률안을 낼 수 있지만, 내용을 살펴보고 결정하는 곳은 국회예요." },
      { id: "court-deliberates-bill", stateId: "submitted-to-assembly", institutionId: "court", specificActor: "법원", actionText: "법률안을 심의해요", feedback: "법률안을 살펴보고 결정하는 일은 국회가 해요." },
      { id: "official-returns-bill", stateId: "passed-by-assembly", institutionId: "executive", specificActor: "행정기관 담당자", actionText: "법률안을 재의하라고 돌려보내요", feedback: "이 사건에서 국회에 다시 살펴 달라고 요청하는 사람은 대통령이에요." },
      { id: "court-promulgates", stateId: "passed-by-assembly", institutionId: "court", specificActor: "법원", actionText: "법률안을 공포해요", feedback: "법원은 법이 만들어졌다고 공식으로 알리는 곳이 아니에요. 지금은 대통령이 할 수 있는 절차를 살펴볼 차례예요." },
    ],
  },
  {
    id: "fictional-science-vehicle-budget",
    kind: "budget",
    title: "가상 공공 과학체험 차량 예산",
    shortTitle: "예산 심의와 집행",
    description: "여러 지역을 방문하는 과학체험 차량 사업이 계획에서 실제 운영까지 어떤 절차를 거치는지 살펴봐요.",
    learningFocus: "정부가 예산안을 편성·제출하고, 국회가 심의·확정하며, 행정부가 확정 예산 안에서 집행해요.",
    initialStateId: "program-plan-ready",
    institutions: ["executive", "national-assembly"],
    legalSourceIds: ["constitution-54", "constitution-66"],
    states: [
      { id: "program-plan-ready", title: "사업 계획만 준비됐어요", documentType: "행정 계획", actor: "행정부", effect: "쓸 수 있는 국가 예산은 아직 없어요.", nextNeed: "정부가 예산안을 편성해야 해요.", answerPosition: 0 },
      { id: "budget-drafted-by-government", title: "정부가 예산안을 편성했어요", documentType: "정부 예산안", actor: "정부", effect: "국회에 제출하기 전 초안이에요.", nextNeed: "국회에 예산안을 제출해야 해요.", answerPosition: 1 },
      { id: "budget-submitted-to-assembly", title: "예산안이 국회에 제출됐어요", documentType: "제출된 예산안", actor: "정부 → 국회", effect: "아직 국가 예산으로 확정되지 않았어요.", nextNeed: "국회의 심의·확정이 필요해요.", answerPosition: 2 },
      { id: "budget-deliberated-and-decided", title: "국회가 예산을 확정했어요", documentType: "확정 예산", actor: "국회", effect: "행정부가 정해진 범위 안에서 집행할 수 있어요.", nextNeed: "행정부가 사업을 집행해요.", answerPosition: 0 },
      { id: "program-executed-within-budget", title: "과학체험 차량 사업이 집행됐어요", documentType: "집행 기록", actor: "행정부", effect: "확정 예산과 법률 범위에서 사업을 운영했어요.", nextNeed: "이 사건의 예산 절차가 끝났어요.", terminal: true },
    ],
    transitions: [
      { id: "budget-draft", fromStateId: "program-plan-ready", actionId: "government-drafts-budget", institutionId: "executive", specificActor: "정부", actionText: "필요한 비용을 예산안에 편성해요", toStateId: "budget-drafted-by-government", relationLabel: "예산안 편성", effectText: "정부가 사업 비용을 예산안에 담았어요.", limitText: "편성만으로 국가 예산이 확정되지는 않아요.", legalSourceIds: ["constitution-54"] },
      { id: "budget-submit", fromStateId: "budget-drafted-by-government", actionId: "government-submits-budget", institutionId: "executive", specificActor: "정부", actionText: "예산안을 국회에 제출해요", toStateId: "budget-submitted-to-assembly", relationLabel: "예산안 제출", effectText: "국회가 예산안을 살펴볼 수 있게 되었어요.", limitText: "정부는 제출하지만 혼자 최종 확정하지 않아요.", legalSourceIds: ["constitution-54"] },
      { id: "budget-decide", fromStateId: "budget-submitted-to-assembly", actionId: "assembly-decides-budget", institutionId: "national-assembly", specificActor: "국회", actionText: "예산안을 심의·확정해요", toStateId: "budget-deliberated-and-decided", relationLabel: "심의·확정", effectText: "국회가 예산안을 살펴 국가 예산으로 확정했어요.", limitText: "국회가 과학체험 차량을 직접 운영하는 것은 아니에요.", legalSourceIds: ["constitution-54"], prediction: { question: "정부가 예산안을 제출하면 바로 사업을 시작할 수 있을까요?", options: [{ id: "assembly", text: "아니요. 국회의 심의·확정이 필요해요." }, { id: "instant", text: "네. 제출한 순간 국가 예산이 돼요." }], correctId: "assembly", explanation: "정부는 예산안을 만들어 국회에 내고, 국회는 내용을 살펴 나라의 예산으로 확정해요." } },
      { id: "budget-execute", fromStateId: "budget-deliberated-and-decided", actionId: "executive-runs-program", institutionId: "executive", specificActor: "행정부", actionText: "확정 예산 안에서 사업을 집행해요", toStateId: "program-executed-within-budget", relationLabel: "예산 집행", effectText: "행정부가 확정된 범위 안에서 과학체험 차량을 운영했어요.", limitText: "국회가 직접 운영자를 채용해 사업을 집행하지 않아요.", legalSourceIds: ["constitution-66"], completesCase: true },
    ],
    misconceptions: [
      { id: "court-drafts-budget", stateId: "program-plan-ready", institutionId: "court", specificActor: "법원", actionText: "사업 예산안을 편성해요", feedback: "정부가 나라의 예산안을 만들어요. 법원은 구체적인 다툼을 재판해요." },
      { id: "assembly-runs-before-budget", stateId: "program-plan-ready", institutionId: "national-assembly", specificActor: "국회", actionText: "차량 사업을 바로 운영해요", feedback: "사업을 시작하기 전에 정부가 예산안을 만들고 국회가 살펴 결정해야 해요." },
      { id: "court-submits-budget", stateId: "budget-drafted-by-government", institutionId: "court", specificActor: "법원", actionText: "예산안을 국회에 제출해요", feedback: "정부가 나라의 예산안을 만들어 국회에 내요." },
      { id: "government-executes-early", stateId: "budget-drafted-by-government", institutionId: "executive", specificActor: "행정부", actionText: "예산 확정 전 사업을 시작해요", feedback: "아직 예산안 단계예요. 먼저 국회에 내고, 국회가 살펴 확정해야 해요." },
      { id: "court-decides-budget", stateId: "budget-submitted-to-assembly", institutionId: "court", specificActor: "법원", actionText: "국가 예산을 확정해요", feedback: "나라의 예산안을 살펴보고 확정하는 곳은 국회예요." },
      { id: "executive-decides-own-budget", stateId: "budget-submitted-to-assembly", institutionId: "executive", specificActor: "정부", actionText: "제출한 예산안을 스스로 확정해요", feedback: "정부는 예산안을 만들어 내고, 국회가 살펴본 뒤 확정해요." },
      { id: "assembly-operates-vehicle", stateId: "budget-deliberated-and-decided", institutionId: "national-assembly", specificActor: "국회", actionText: "차량 운영자를 직접 채용해요", feedback: "국회는 예산을 확인하고, 실제 차량 사업은 행정부가 운영해요." },
      { id: "court-operates-vehicle", stateId: "budget-deliberated-and-decided", institutionId: "court", specificActor: "법원", actionText: "과학체험 차량을 운영해요", feedback: "법원은 행정 사업을 직접 운영하지 않아요." },
    ],
  },
  {
    id: "fictional-mobile-library-administrative-disposition",
    kind: "administrative-disposition",
    title: "가상 이동식 도서관 지원 거부처분",
    shortTitle: "처분과 행정재판",
    description: "가상 법률에 없는 조건으로 지원 신청을 거부한 결정이 재판을 거쳐 다시 처리돼요.",
    learningFocus: "법원은 처분의 위법 여부를 독립하여 판단하고, 행정기관은 판결 취지에 맞게 다시 처리해요.",
    initialStateId: "application-received",
    institutions: ["executive", "court", "national-assembly"],
    legalSourceIds: ["constitution-101-103", "constitution-107", "supreme-court-administrative"],
    states: [
      { id: "application-received", title: "지원 신청이 접수됐어요", documentType: "지원 신청서", actor: "행정기관", effect: "가상 법률의 조건에 따라 살펴볼 차례예요.", nextNeed: "행정기관이 처분을 결정해요.", answerPosition: 1 },
      { id: "application-denied-by-disposition", title: "거부처분이 내려졌어요", documentType: "행정처분", actor: "행정기관", effect: "가상 법률에 없는 추가 조건이 거부 이유에 들어갔어요.", nextNeed: "영향을 받은 단체가 취소를 구할 수 있어요.", answerPosition: 2 },
      { id: "administrative-lawsuit-filed", title: "행정소송이 제기됐어요", documentType: "소장", actor: "가상 비영리단체 → 법원", effect: "구체적인 다툼을 법원이 살펴볼 수 있어요.", nextNeed: "법원이 주장과 자료를 심리해요.", answerPosition: 0 },
      { id: "court-reviewed-legality", title: "법원이 처분의 위법 여부를 살폈어요", documentType: "재판 기록", actor: "법원", effect: "가상 법률과 처분 이유를 독립하여 비교했어요.", nextNeed: "사건 자료에 따라 판결해요.", answerPosition: 1 },
      { id: "disposition-cancelled", title: "법원이 거부처분을 취소했어요", documentType: "취소 판결", actor: "법원", effect: "거부처분의 효력이 사라졌지만 신청이 자동 승인된 것은 아니에요.", nextNeed: "행정기관이 판결 취지에 맞게 다시 처리해요.", answerPosition: 2 },
      { id: "returned-for-administrative-reprocessing", title: "행정기관이 신청을 다시 처리했어요", documentType: "재처리 기록", actor: "행정기관", effect: "판결 취지와 가상 법률에 따라 다시 판단했어요.", nextNeed: "이 사건의 처리 절차가 끝났어요.", terminal: true },
    ],
    transitions: [
      { id: "disposition-deny", fromStateId: "application-received", actionId: "agency-issues-denial", institutionId: "executive", specificActor: "행정기관", actionText: "신청에 거부처분을 내려요", toStateId: "application-denied-by-disposition", relationLabel: "행정처분", effectText: "행정기관이 신청을 거부하는 처분을 내렸어요.", limitText: "이 사건 자료에는 가상 법률에 없는 조건이 처분 이유로 적혀 있어요.", legalSourceIds: ["constitution-66"] },
      { id: "lawsuit-file", fromStateId: "application-denied-by-disposition", actionId: "group-files-lawsuit", institutionId: "court", specificActor: "영향을 받은 가상 단체", actorKind: "participant", actionText: "법원에 처분 취소를 구하는 소송을 내요", toStateId: "administrative-lawsuit-filed", relationLabel: "행정소송", effectText: "구체적인 처분을 둘러싼 다툼이 법원에 접수됐어요.", limitText: "법원이 정책 찬반을 정하는 활동은 아니에요.", legalSourceIds: ["supreme-court-administrative"] },
      { id: "court-review", fromStateId: "administrative-lawsuit-filed", actionId: "court-reviews-legality", institutionId: "court", specificActor: "법원", actionText: "당사자 주장과 가상 법률을 살펴요", toStateId: "court-reviewed-legality", relationLabel: "독립된 심리", effectText: "법원이 처분의 위법 여부를 독립하여 살폈어요.", limitText: "법원은 새 지원 정책을 직접 만들지 않아요.", legalSourceIds: ["constitution-101-103", "supreme-court-administrative"] },
      { id: "court-cancel", fromStateId: "court-reviewed-legality", actionId: "court-cancels-disposition", institutionId: "court", specificActor: "법원", actionText: "위법한 거부처분을 취소해요", toStateId: "disposition-cancelled", relationLabel: "취소 판결", effectText: "법원이 거부처분을 취소했어요. 신청이 자동 승인된 것은 아니에요.", limitText: "법원이 승인 내용을 대신 정하거나 사업을 집행하지 않아요.", legalSourceIds: ["constitution-101-103", "constitution-107", "supreme-court-administrative"], prediction: { question: "거부처분이 취소되면 다음에는 누가 무엇을 할까요?", options: [{ id: "reprocess", text: "행정기관이 판결 취지와 법률에 따라 다시 처리해요." }, { id: "court-approve", text: "법원이 지원 사업을 직접 승인하고 운영해요." }], correctId: "reprocess", explanation: "법원은 법에 어긋난 결정을 취소하고, 행정기관은 판결이 뜻하는 내용에 맞게 다시 처리해요." } },
      { id: "agency-reprocess", fromStateId: "disposition-cancelled", actionId: "agency-reprocesses-application", institutionId: "executive", specificActor: "행정기관", actionText: "판결 취지에 맞게 신청을 다시 처리해요", toStateId: "returned-for-administrative-reprocessing", relationLabel: "행정 재처리", effectText: "행정기관이 가상 법률과 판결 취지에 따라 다시 처리했어요.", limitText: "취소 판결을 무시하고 같은 이유로 즉시 거부할 수는 없어요.", legalSourceIds: ["supreme-court-administrative"], completesCase: true },
    ],
    misconceptions: [
      { id: "assembly-decides-application", stateId: "application-received", institutionId: "national-assembly", specificActor: "국회", actionText: "개별 신청을 판결해요", feedback: "국회는 개인이나 단체의 신청을 판결하지 않아요. 행정기관이 신청을 처리해요." },
      { id: "court-runs-library", stateId: "application-received", institutionId: "court", specificActor: "법원", actionText: "도서관 지원 사업을 운영해요", feedback: "법원은 지원 사업을 직접 운영하지 않아요. 행정기관이 법에 따라 운영해요." },
      { id: "assembly-files-ruling", stateId: "application-denied-by-disposition", institutionId: "national-assembly", specificActor: "국회", actionText: "거부처분을 판결로 취소해요", feedback: "행정기관의 결정이 법에 맞는지는 소송이 시작된 뒤 법원이 재판해요." },
      { id: "agency-judges-itself", stateId: "application-denied-by-disposition", institutionId: "executive", specificActor: "행정기관", actionText: "자기 처분이 합법이라고 최종 판결해요", feedback: "행정기관은 결정을 내리지만, 그 결정을 둘러싼 재판은 법원이 맡아요." },
      { id: "assembly-hears-case", stateId: "administrative-lawsuit-filed", institutionId: "national-assembly", specificActor: "국회", actionText: "개별 사건 재판을 진행해요", feedback: "구체적인 법적 다툼은 법원이 재판해요." },
      { id: "agency-dismisses-lawsuit", stateId: "administrative-lawsuit-filed", institutionId: "executive", specificActor: "행정기관", actionText: "제기된 소송을 끝내요", feedback: "소송이 시작된 뒤에는 법원이 주장과 자료를 살펴요." },
      { id: "assembly-cancels-disposition", stateId: "court-reviewed-legality", institutionId: "national-assembly", specificActor: "국회", actionText: "개별 거부처분을 판결로 취소해요", feedback: "이 구체적인 다툼은 법원이 재판해 판단해요." },
      { id: "court-directly-approves", stateId: "court-reviewed-legality", institutionId: "court", specificActor: "법원", actionText: "신청을 직접 승인하고 사업을 운영해요", feedback: "법원은 행정기관의 결정이 법에 맞는지 판단하지만, 지원 사업을 직접 운영하지 않아요." },
      { id: "agency-ignores-ruling", stateId: "disposition-cancelled", institutionId: "executive", specificActor: "행정기관", actionText: "같은 이유로 즉시 다시 거부해요", feedback: "판결이 뜻하는 내용과 가상 법률에 따라 신청을 다시 처리해야 해요." },
      { id: "court-reprocesses", stateId: "disposition-cancelled", institutionId: "court", specificActor: "법원", actionText: "행정기관 대신 신청을 다시 처리해요", feedback: "법원은 판결하고, 실제 신청 처리는 행정기관이 맡아요." },
    ],
  },
];
